# wrangler.toml — Cognomega API Worker (prod)
# Routes all traffic for api.cognomega.com to a single Worker.

name               = "cognomega-api"
main               = "src/index.ts"
compatibility_date = "2025-09-03"
workers_dev        = false
logpush            = false  # optional (enable in CF dashboard if you want)

# Route everything under the zone to this Worker
routes = [
  { pattern = "api.cognomega.com/*", zone_name = "cognomega.com" }
]

# ---------- Bindings ----------

# Cloudflare Workers AI
[ai]
binding = "AI"

# KV namespaces
# KEYS: JWKS (public JSON at /.well-known/jwks.json)
[[kv_namespaces]]
binding = "KEYS"
id      = "7e9d002852ba44849900a2babfcaf816"

# KV_BILLING: credits + usage + jobs (module-backed)
[[kv_namespaces]]
binding = "KV_BILLING"
id      = "5da314a8b48b4db684678ab5ad074563"

# KV_PREFS: per-user voice preferences
[[kv_namespaces]]
binding = "KV_PREFS"
id      = "ef783de622644eb89ff2dacfcc41a2f2"

# R2 buckets
# Keep BOTH: legacy routes may use R2, new module uses R2_UPLOADS.
[[r2_buckets]]
binding     = "R2"                 # legacy artifacts bucket
bucket_name = "cognomega-prod"

[[r2_buckets]]
binding     = "R2_UPLOADS"         # direct-upload bucket (auth/billing module)
bucket_name = "cognomega-uploads"

# ---------- Vars (non-secrets) ----------

ALLOW_PROVIDERS = "local"
PREFERRED_PROVIDER = "local"
[triggers]
crons = ["*/5 * * * *"]  # queue kicker for Neon jobs (up to 5 per tick)

[vars]
ALLOW_PROVIDERS = "local"
PREFERRED_PROVIDER = "local"
