name: Uptime

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check /ready
        run: |
          set -e
          code=$(curl -s -o /tmp/ready.json -w "%{http_code}" https://api.cognomega.com/ready)
          cat /tmp/ready.json
          test "$code" = "200"

      - name: Parse /ready JSON
        run: |
          provider=$(jq -r '.provider // empty' /tmp/ready.json || true)
          model=$(jq -r '.model // empty' /tmp/ready.json || true)
          echo "Provider: ${provider:-n/a}"
          echo "Model: ${model:-n/a}"

      - name: Preflight CORS (OPTIONS /api/si/ask)
        run: |
          code=$(curl -i -s -o /tmp/opts.txt -w "%{http_code}" -X OPTIONS \
            -H "Origin: https://app.cognomega.com" \
            -H "Access-Control-Request-Method: POST" \
            -H "Access-Control-Request-Headers: content-type, x-user-email, x-intelligence-tier" \
            https://api.cognomega.com/api/si/ask)
          grep -i "Access-Control-Allow-Methods" /tmp/opts.txt
          grep -i "Access-Control-Allow-Headers" /tmp/opts.txt
          test "$code" = "204"

      # Optional smoke for SI (requires seeded credits + test email)
      - name: SI ask smoke (non-fatal)
        continue-on-error: true
        env:
          TEST_EMAIL: vihaan@cognomega.com
        run: |
          curl -s -X POST https://api.cognomega.com/api/si/ask \
            -H "Origin: https://app.cognomega.com" \
            -H "Content-Type: application/json" \
            -H "X-User-Email: $TEST_EMAIL" \
            -d '{"skill":"summarize","input":"uptime probe"}' \
            | jq
