name = "cognomega-api"
main = "src/index.ts"
compatibility_date = "2025-09-03"

[vars]
# Optional: set at deploy-time via wrangler secret put instead.
# LLM_BASE_URL = "https://your-llm-router.example.com"
# LLM_COMPLETE_PATH = "/api/v1/llm/complete"

# If you also want R2 in this worker later:
# [[r2_buckets]]
# binding = "R2"
# bucket_name = "cognomega-prod"


[ai]
binding = "AI"

routes = [{ pattern = "api.cognomega.com/*", zone_name = "cognomega.com" }]
[triggers]
crons = ["*/5 * * * *"]
[[r2_buckets]]
binding = "R2"
bucket_name = "cognomega-prod"
