name = "cognomega-api"
main = "src/index.ts"
compatibility_date = "2024-09-02"

[vars]
JWT_ISS = "cognomega"
JWT_AUD = "cognomega-clients"

[[kv_namespaces]]
binding = "CREDITS"
id = "CREDITS_NAMESPACE_ID"

[[r2_buckets]]
binding = "FILES"
bucket_name = "cognomega-files"
