# wrangler.toml — Cognomega API Worker (prod)

name                = "cognomega-api"
main                = "src/index.ts"
compatibility_date  = "2025-09-03"
workers_dev         = false         # we use zone routes instead of *.workers.dev
logpush             = true          # enable Logpush (optional; safe to keep)

# Route *everything* under api.cognomega.com to this Worker
routes = [
  { pattern = "api.cognomega.com/*", zone_name = "cognomega.com" }
]

# --- Bindings ---

# Cloudflare AI (used by some endpoints; safe to keep even if unused)
[ai]
binding = "AI"

# R2 bucket (present + ready; keep if you plan to stream uploads/exports)
[[r2_buckets]]
binding     = "R2"
bucket_name = "cognomega-prod"

# Static, non-secret config can live here (optional).
[vars]
# If your code reads these, you can configure CORS w/o redeploying code.
# ALLOWED_ORIGINS = "https://app.cognomega.com,https://builder.cognomega.com,http://localhost:5174,http://localhost:5173"
# TOKEN_TTL_SEC   = "3600"

# If you use scheduled jobs (e.g., usage rollups), keep this.
[triggers]
crons = ["*/5 * * * *"]

# ---- Optional: environment blocks (uncomment if you want per-env routes) ----
# [env.staging]
# name    = "cognomega-api-staging"
# routes  = [{ pattern = "staging-api.cognomega.com/*", zone_name = "cognomega.com" }]
# workers_dev = false
#
# [env.dev]
# name    = "cognomega-api-dev"
# workers_dev = true
