name: ci
on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build --if-present
      - run: pnpm -r run check --if-present
      - run: pnpm -r run test --if-present
