name: codex-commands

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  handle:
    # TEMP WINDOW: no label guard; still restricted to issues (not PR review comments)
    if: ${{ github.event.issue.pull_request == null && startsWith(github.event.comment.body, '/codex-') }}
    runs-on: ubuntu-latest
    steps:
      - name: Log command (guard disabled window)
        run: |
          echo "actor=${{ github.actor }}"
          echo "issue=${{ github.event.issue.number }}"
          echo "body=${{ github.event.comment.body }}"
