name: deploy-builder
on:
  push:
    branches: [main]
    paths:
      - "packages/builder/**"
      - ".github/workflows/deploy-builder.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate

      - name: Install deps (workspace)
        run: pnpm install --frozen-lockfile

      - name: Build builder
        working-directory: packages/builder
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler@4 pages deploy packages/builder/dist --project-name cognomega-builder
