name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    environment: production
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Install wrangler
        run: npm i -g wrangler@3

      - name: Deploy API worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          cd api
          wrangler deploy --config wrangler.toml --env production

  probes:
    runs-on: ubuntu-latest
    needs: deploy-worker
    steps:
      - name: Run production probes
        env:
          API: https://api.cognomega.com
          ORIGIN: https://app.cognomega.com
        run: |
          set -euo pipefail
          stamp=$(date -u +%Y%m%d-%H%M%S)
          mkdir -p ops/proofs

          # 1) Preflight
          curl -i -s -X OPTIONS "$API/api/si/ask" \
            -H "Origin: $ORIGIN" \
            -H "Access-Control-Request-Method: POST" \
            -H "Access-Control-Request-Headers: content-type, x-user-email, x-intelligence-tier" \
            > ops/proofs/${stamp}-preflight.txt

          # 2) JWKS (first 120)
          jwks=$(curl -s "$API/.well-known/jwks.json")
          echo "${jwks:0:120}" > ops/proofs/${stamp}-jwks-head.txt

          # 3) AI binding
          curl -s "$API/api/ai/binding" > ops/proofs/${stamp}-ai-binding.json

          # 4) Guest token sanity
          tok=$(curl -s -X POST "$API/auth/guest" | jq -r .token)
          hdr=$(echo "$tok" | cut -d. -f1 | base64 -d 2>/dev/null || true)
          pay=$(echo "$tok" | cut -d. -f2 | base64 -d 2>/dev/null || true)
          echo "$hdr" > ops/proofs/${stamp}-guest-hdr.json || true
          echo "$pay" > ops/proofs/${stamp}-guest-payload.json || true

          # 5) Credits/balance check (bearer only, should resolve guest)
          curl -s "$API/api/billing/balance" -H "Authorization: Bearer $tok" \
            > ops/proofs/${stamp}-balance-guest.json

          # Fail-fast assertions (basic)
          jq -e '.ai_bound == true' ops/proofs/${stamp}-ai-binding.json >/dev/null
          jq -e '.iss=="https://api.cognomega.com"' ops/proofs/${stamp}-guest-payload.json >/dev/null

      - name: Upload proofs
        uses: actions/upload-artifact@v4
        with:
          name: production-proofs
          path: ops/proofs
