name: deploy

on:
  push:
    branches: [ main ]
    paths:
      - "api/**"
      - "api/wrangler.toml"
      - ".github/workflows/deploy.yml"   # allow changes to this file to test itself
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://api.cognomega.com
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Wrangler
        run: npm i -g wrangler@3
      - name: Install API deps
        working-directory: api
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm i --no-frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi
      - name: Deploy (wrangler)
        working-directory: api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: wrangler deploy
      - name: Probes
        run: |
          set -e
          base="https://api.cognomega.com"
          echo "== ai/binding =="                        | tee probes.txt
          curl -sS "$base/api/ai/binding"               | tee -a probes.txt
          echo "\n== jwks (head 120) =="                 | tee -a probes.txt
          curl -sS "$base/.well-known/jwks.json" | head -c 120 | tee -a probes.txt
          echo "\n== preflight si =="                    | tee -a probes.txt
          curl -sSI -X OPTIONS "$base/api/si/ask" \
            -H "Origin: https://app.cognomega.com" \
            -H "Access-Control-Request-Method: POST" \
            -H "Access-Control-Request-Headers: content-type, x-user-email, x-intelligence-tier" \
            | tee -a probes.txt
      - name: Upload proofs
        uses: actions/upload-artifact@v4
        with:
          name: post-deploy-proofs
          path: probes.txt
