name: deploy-frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # required
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      # set this secret to your Pages project name (e.g. app-cognomega)
      PAGES_PROJECT_NAME: ${{ secrets.PAGES_PROJECT_NAME }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install & build
        working-directory: frontend
        run: |
          npm ci || npm i
          npm run build

      - name: Deploy to Cloudflare Pages
        working-directory: frontend
        run: npx wrangler@4 pages deploy dist --project-name "$PAGES_PROJECT_NAME" --branch main
