name: deploy

on:
  push:
    branches: [main]
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy API (CF Workers)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required secrets present
        run: |
          set -e
          [ -n "$CLOUDFLARE_API_TOKEN" ] || { echo "::error::CLOUDFLARE_API_TOKEN secret is missing"; exit 1; }
          [ -n "$CLOUDFLARE_ACCOUNT_ID" ]  || { echo "::error::CLOUDFLARE_ACCOUNT_ID secret is missing"; exit 1; }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Wrangler
        run: npm i -g wrangler@3

      - name: Who am I (debug auth)
        working-directory: api
        run: |
          wrangler --version
          wrangler whoami || true

      - name: Show wrangler.toml (first lines)
        working-directory: api
        run: sed -n '1,120p' wrangler.toml || true

      - name: Deploy (wrangler)
        working-directory: api
        run: |
          # if you use envs like [env.production], add:  wrangler deploy --env production
          wrangler deploy --config wrangler.toml
