name: Deploy Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  preview-cloudflare:
    name: Preview on Cloudflare Pages
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: |
          cd packages/frontend
          pnpm run build

      - name: Deploy to Cloudflare Pages (Preview)
        id: cloudflare
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cognomega-edge
          directory: packages/frontend/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Cloudflare preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.cloudflare.outputs.url }}';
            const comment = `### 🚀 Cloudflare Preview Deployed
            
            Preview URL: ${url}
            
            ✅ Preview environment is ready for testing!`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  preview-vercel:
    name: Preview on Vercel
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: vars.ENABLE_VERCEL_PREVIEW == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build frontend
        run: |
          cd packages/frontend
          pnpm run build

      - name: Deploy to Vercel (Preview)
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: packages/frontend/dist
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with Vercel preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.vercel.outputs.preview-url }}';
            const comment = `### 🚀 Vercel Preview Deployed
            
            Preview URL: ${url}
            
            ✅ Preview environment is ready for testing!`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
