name: proofs-gate
on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
permissions:
  contents: read
jobs:
  require-proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if sensitive changes present
        id: scan
        run: |
          set -euo pipefail
          PR_LABELS="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          echo "labels=$PR_LABELS" >> $GITHUB_OUTPUT
          # if any of these labels are on the PR, require proofs
          if [[ "$PR_LABELS" =~ (change:routes|change:cors|change:headers) ]]; then
            echo "needs_proofs=true" >> $GITHUB_OUTPUT
          else
            echo "needs_proofs=false" >> $GITHUB_OUTPUT
          fi

      - name: Enforce proofs present
        if: steps.scan.outputs.needs_proofs == 'true'
        run: |
          set -euo pipefail
          base="origin/${{ github.base_ref }}"
          git fetch --no-tags origin "${{ github.base_ref }}:${{ github.base_ref }}"
          CHANGED=$(git diff --name-only "$base"...HEAD | grep '^ops/proofs/' || true)
          if [ -z "$CHANGED" ]; then
            echo "::error::Sensitive change detected but no files under ops/proofs/ were added/updated."
            echo "Add route/CORS/JWKS/guest/preflight proofs and apply label ops:proofs-attached."
            exit 1
          fi
          echo "Proofs detected:"
          echo "$CHANGED"
