name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run unit tests
        run: pnpm -r --if-present test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/coverage/
            **/test-results/
          retention-days: 7

  e2e-tests:
    name: E2E Tests (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - run: corepack enable && corepack prepare pnpm@10.15.1 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: |
          if [ -f "packages/frontend/package.json" ]; then
            cd packages/frontend
            if grep -q "@playwright/test" package.json; then
              npx playwright install --with-deps chromium
            fi
          fi

      - name: Build applications
        run: pnpm -r --if-present build

      - name: Run E2E tests
        run: |
          if [ -f "packages/frontend/package.json" ]; then
            cd packages/frontend
            if grep -q "@playwright/test" package.json; then
              pnpm test:e2e || true
            fi
          fi

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            packages/frontend/playwright-report/
            packages/frontend/test-results/
          retention-days: 7
