name: uptime
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping ready endpoint
        shell: bash
        run: |
          set -euo pipefail
          URL="https://api.cognomega.com/ready"
          CODE=$(curl -sS -w "%{http_code}" -o /tmp/body "$URL")
          echo "HTTP: $CODE"
          echo "Body:"; cat /tmp/body; echo
          test "$CODE" = "200"
