name: uptime
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Ping ready endpoint
        run: |
          set -e
          URL='https://api.cognomega.com/ready'
          CODE=\
          echo "HTTP: \"
          echo "Body:"; cat /tmp/body; echo
          test "\" = "200"
